export const GOOGLE_KEY = {
    key: 'AIzaSyDNp6uFgiZS7vLJdxqivmAeRjb4B6t8kP4'
};

export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';
export const FETCH_NEW_BOOKS = 'FETCH_NEW_BOOKS';
export const FETCH_NEW_BOOKS_SUCCESS = 'FETCH_NEW_BOOKS_SUCCES';
export const FETCH_NEW_BOOKS_ERROR = 'FETCH_NEW_BOOKS_ERROR';
export const FETCH_BOOK_CARD = 'FETCH_BOOK_CARD';
export const FETCH_BOOK_CARD_SUCCESS = 'FETCH_BOOK_CARD_SUCCESS';
export const FETCH_BOOK__CARD_ERROR = 'FETCH_BOOK__CARD_ERROR';
export const SET_ERROR = "SET_ERROR";



